# Generated by Django 5.2 on 2025-05-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_blog_section_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('1', 'PUBLISH'), ('0', 'DRAFT')], default=0, max_length=1),
        ),
    ]
