# Generated by Django 5.2 on 2025-04-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='name',
            new_name='name_of_school',
        ),
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.CharField(choices=[('Accra', 'Greater Accra'), ('Central', 'Central'), ('Western', 'Western'), ('Northern', 'Northern'), ('Ashanti', 'Ashanti'), ('Eastern', 'Eastern'), ('Volta', 'Volta'), ('Ahafo', 'Ahafo'), ('Bono', 'Bono'), ('Bono East', 'Bono East'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Savannah', 'Savannah'), ('North East', 'North East'), ('Oti', 'Oti'), ('Western North', 'Western North')], default='Not Selected', max_length=20),
        ),
    ]
