# Generated by Django 5.2 on 2025-04-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_name_school_name_of_school_school_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
