# Generated by Django 5.2 on 2025-05-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_document_alter_contestant_year_form'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('school', 'coach_type')},
        ),
    ]
